package handlers

import (
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/zyranet/zyranet-api/config"
	"github.com/zyranet/zyranet-api/middleware"
	"github.com/zyranet/zyranet-api/models"
	"github.com/zyranet/zyranet-api/utils"
)

// resolveHotspotZone finds the zone a captive-portal request belongs to.
// The customer app forwards the ?zone= query param it received from the
// router's login redirect (see App.vue/usePortalParams.js and the
// zone-embedded login.html generated by ZoneCaptiveLoginHTML) as either a
// query param or a body field named zoneID. Falling back to the first zone
// in the DB preserves behavior for any router still running an
// older-generation script/login.html that doesn't pass a zone yet.
func resolveHotspotZone(c *fiber.Ctx, zoneIDStr string) (*models.Zone, error) {
	var zone models.Zone
	if zoneIDStr == "" {
		zoneIDStr = c.Query("zone_id")
	}
	if zoneIDStr != "" {
		if err := config.DB.First(&zone, zoneIDStr).Error; err == nil {
			return &zone, nil
		}
	}
	if err := config.DB.First(&zone).Error; err != nil {
		return nil, err
	}
	return &zone, nil
}

// HotspotPay handles payment initiation from the captive portal.
func HotspotPay(c *fiber.Ctx) error {
	var body struct {
		Phone  string `json:"phone"`
		PlanID string `json:"plan_id"`
		Mac    string `json:"mac"`
		IP     string `json:"ip"`
		ZoneID string `json:"zone_id"`
	}

	if err := c.BodyParser(&body); err != nil {
		return utils.ErrorResponse(c, "Invalid request body.", "", fiber.StatusBadRequest)
	}

	if body.Phone == "" || body.PlanID == "" {
		return utils.ErrorResponse(c, "phone and plan_id are required.", "", fiber.StatusUnprocessableEntity)
	}

	phone := utils.FormatPhone(body.Phone)

	zonePtr, err := resolveHotspotZone(c, body.ZoneID)
	if err != nil {
		return utils.ErrorResponse(c, "No zone configured on the server.", "", fiber.StatusInternalServerError)
	}
	zone := *zonePtr

	// Map plan_id to package details
	var price float64
	var speedDown, speedUp int
	var name string

	switch strings.ToLower(body.PlanID) {
	case "basic":
		price = 20
		speedDown = 2048
		speedUp = 1024
		name = "Basic"
	case "premium":
		price = 50
		speedDown = 10240
		speedUp = 5120
		name = "Premium"
	default: // standard
		price = 30
		speedDown = 5120
		speedUp = 2048
		name = "Standard"
	}

	// Find or create package in DB
	var pkg models.Package
	if err := config.DB.Where("price = ? AND type = ? AND zone_id = ?", price, "hotspot", zone.ID).First(&pkg).Error; err != nil {
		pkg = models.Package{
			ZoneID:            zone.ID,
			Name:              name,
			Type:              "hotspot",
			Price:             price,
			BillingCycle:      "daily",
			SpeedDownloadKbps: speedDown,
			SpeedUploadKbps:   speedUp,
			Status:            "active",
		}
		if err := config.DB.Create(&pkg).Error; err != nil {
			return utils.ErrorResponse(c, err.Error(), "Failed to create package.", fiber.StatusInternalServerError)
		}
	}

	// Auto-generate voucher
	voucher, err := voucherSvcGlobal.Generate(zone.ID, pkg.ID, "single_use", 1)
	if err != nil {
		return utils.ErrorResponse(c, err.Error(), "Failed to prepare voucher.", fiber.StatusInternalServerError)
	}

	var customerID *uint
	var existingCustomer models.Customer
	if err := config.DB.Where("phone = ?", phone).First(&existingCustomer).Error; err == nil {
		customerID = &existingCustomer.ID
	} else if body.Mac != "" {
		var dev models.CustomerDevice
		if err := config.DB.Where("mac_address = ?", body.Mac).First(&dev).Error; err == nil {
			customerID = &dev.CustomerID
		}
	}

	// Create pending payment record
	payment := models.Payment{
		CustomerID: customerID,
		VoucherID:  &voucher.ID,
		ZoneID:     zone.ID,
		PackageID:  &pkg.ID,
		Phone:      phone,
		Amount:     pkg.Price,
		Currency:   "KES",
		Method:     "mpesa",
		Status:     "pending",
		MacAddress: body.Mac,
		IpAddress:  body.IP,
	}

	if err := config.DB.Create(&payment).Error; err != nil {
		return utils.ErrorResponse(c, err.Error(), "Failed to create payment record.", fiber.StatusInternalServerError)
	}

	ref := fmt.Sprintf("Vouch%d", voucher.ID)
	description := "WiFi"
	if pkg.Name != "" {
		description = pkg.Name
	}

	stkResp, err := mpesaSvcGlobal.InitiateSTKPush(zone.ID, phone, pkg.Price, ref, description)
	if err != nil {
		reason := err.Error()
		config.DB.Model(&payment).Updates(map[string]interface{}{
			"status":        "failed",
			"status_reason": reason,
		})
		return utils.ErrorResponse(c, err.Error(), "M-Pesa API error.", fiber.StatusInternalServerError)
	}

	if stkResp.Status == "success" {
		config.DB.Model(&payment).Update("mpesa_transaction_id", stkResp.CheckoutRequestID)

		// Simulate callback in mock/sandbox mode
		if stkResp.IsMock {
			mpesaSvcGlobal.SimulateCallback(stkResp.CheckoutRequestID, pkg.Price, phone)
		}

		return c.JSON(fiber.Map{
			"reference": stkResp.CheckoutRequestID,
			"message":   "STK Push initiated successfully.",
		})
	}

	reason := "Failed to initiate M-Pesa STK Push payment."
	config.DB.Model(&payment).Updates(map[string]interface{}{
		"status":        "failed",
		"status_reason": reason,
	})
	return utils.ErrorResponse(c, reason, "", fiber.StatusBadRequest)
}

// HotspotStatus checks payment status for polling.
func HotspotStatus(c *fiber.Ctx) error {
	ref := c.Params("reference")
	if ref == "" {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"status": "failed", "message": "Reference is required"})
	}

	var payment models.Payment
	if err := config.DB.Where("mpesa_transaction_id = ?", ref).First(&payment).Error; err != nil {
		return c.Status(fiber.StatusNotFound).JSON(fiber.Map{"status": "failed", "message": "Payment record not found"})
	}

	buildPaidResponse := func(p *models.Payment) fiber.Map {
		resp := fiber.Map{"status": "paid"}
		pkgID := uint(0)
		if p.PackageID != nil {
			pkgID = *p.PackageID
		}
		pkgTag := fmt.Sprintf("pkg-%d", pkgID)
		var pkg models.Package
		if pkgID > 0 && config.DB.First(&pkg, pkgID).Error == nil {
			if pkg.IsFreeTier || pkg.Price == 0 {
				pkgTag = "free"
			}
		}
		resp["username"] = pkgTag
		resp["password"] = pkgTag
		if p.CustomerID != nil && *p.CustomerID > 0 {
			token, _ := middleware.GenerateCustomerToken(*p.CustomerID)
			middleware.SetAuthCookie(c, middleware.CustomerCookieName, token)
			resp["token"] = token
			resp["customer_id"] = *p.CustomerID
		}
		return resp
	}

	if payment.Status == "completed" {
		return c.JSON(buildPaidResponse(&payment))
	} else if payment.Status == "failed" {
		msg := "Payment failed"
		if payment.StatusReason != nil {
			msg = *payment.StatusReason
		}
		return c.JSON(fiber.Map{"status": "failed", "message": msg})
	}

	// Reconcile status with M-Pesa query API as a fallback if the transaction is pending
	if payment.Status == "pending" && mpesaSvcGlobal != nil {
		newStatus, err := mpesaSvcGlobal.QueryAndUpdateSTKStatus(&payment)
		if err == nil {
			if newStatus == "completed" {
				return c.JSON(buildPaidResponse(&payment))
			} else if newStatus == "failed" {
				msg := "Payment failed"
				if payment.StatusReason != nil {
					msg = *payment.StatusReason
				}
				return c.JSON(fiber.Map{"status": "failed", "message": msg})
			}
		} else {
			log.Printf("[M-Pesa] Error querying STK status: %v", err)
		}
	}

	return c.JSON(fiber.Map{"status": "pending"})
}

// HotspotSession returns the active session stats for a MAC address.
func HotspotSession(c *fiber.Ctx) error {
	mac := c.Query("mac")
	if mac == "" {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"active": false, "error": "mac is required"})
	}

	cleanMac := strings.ToLower(strings.TrimSpace(mac))
	cleanMac = strings.ReplaceAll(cleanMac, "-", ":")
	now := time.Now()

	// 1. Check Customer in DB for active unexpired subscription matching this MAC
	var customer models.Customer
	foundCustomer := false

	// Try finding by direct MAC address
	if err := config.DB.Preload("Package").Preload("Zone").
		Where("(LOWER(mac_address) = ? OR REPLACE(LOWER(mac_address), '-', ':') = ?) AND status = ? AND expires_at > ?", cleanMac, cleanMac, "active", now).
		Order("expires_at DESC").First(&customer).Error; err == nil {
		foundCustomer = true
	}

	// Also check through CustomerDevice
	if !foundCustomer {
		var dev models.CustomerDevice
		if err := config.DB.Preload("Customer.Package").Preload("Customer.Zone").
			Where("LOWER(mac_address) = ? OR REPLACE(LOWER(mac_address), '-', ':') = ?", cleanMac, cleanMac).
			Order("last_seen_at DESC").First(&dev).Error; err == nil && dev.Customer != nil {
			if dev.Customer.Status == "active" && dev.Customer.ExpiresAt != nil && dev.Customer.ExpiresAt.After(now) {
				customer = *dev.Customer
				foundCustomer = true
			}
		}
	}

	// Also check if customer is authenticated via session cookie
	if !foundCustomer {
		if claims := middleware.OptionalCustomerClaims(c); claims != nil && claims.CustomerID > 0 {
			if err := config.DB.Preload("Package").Preload("Zone").
				Where("id = ? AND status = ? AND expires_at > ?", claims.CustomerID, "active", now).
				First(&customer).Error; err == nil {
				foundCustomer = true
			}
		}
	}

	// Also check recent completed payment for this MAC
	if !foundCustomer {
		var payment models.Payment
		if err := config.DB.Preload("Package").Preload("Zone").
			Where("(LOWER(mac_address) = ? OR REPLACE(LOWER(mac_address), '-', ':') = ?) AND status = ?", cleanMac, cleanMac, "completed").
			Order("created_at DESC").First(&payment).Error; err == nil && payment.Package != nil {
			validUntil := utils.CalculateExpiry(payment.Package.BillingCycle, &payment.CreatedAt, payment.Package.TimeLimitMinutes)
			if validUntil.After(now) {
				timeLeft := int64(time.Until(validUntil).Seconds())
				speed := fmt.Sprintf("%.0f Mbps", float64(payment.Package.SpeedDownloadKbps)/1024)
				return c.JSON(fiber.Map{
					"active":     true,
					"plan_name":  payment.Package.Name,
					"speed":      speed,
					"time_left":  timeLeft,
					"expires_at": validUntil,
					"bytes_in":   104857600,
					"bytes_out":  20971520,
				})
			}
		}
	}

	if foundCustomer && customer.Package != nil && customer.ExpiresAt != nil && customer.ExpiresAt.After(now) {
		timeLeft := int64(time.Until(*customer.ExpiresAt).Seconds())
		speed := fmt.Sprintf("%.0f Mbps", float64(customer.Package.SpeedDownloadKbps)/1024)
		return c.JSON(fiber.Map{
			"active":     true,
			"plan_name":  customer.Package.Name,
			"speed":      speed,
			"time_left":  timeLeft,
			"expires_at": *customer.ExpiresAt,
			"bytes_in":   104857600,
			"bytes_out":  20971520,
		})
	}

	zone, err := resolveHotspotZone(c, "")
	if err == nil && mikrotikSvc != nil {
		sessions, err := mikrotikSvc.GetActiveSessions(zone)
		if err == nil {
			for _, s := range sessions {
				if strings.EqualFold(s.MAC, cleanMac) || strings.EqualFold(s.MAC, mac) {
					return c.JSON(fiber.Map{
						"active":    true,
						"plan_name": "Standard",
						"speed":     "5 Mbps",
						"time_left": 86400,
						"bytes_in":  s.BytesIn,
						"bytes_out": s.BytesOut,
					})
				}
			}
		}
	}

	return c.JSON(fiber.Map{"active": false})
}

// HotspotLogout disconnects a client by MAC.
func HotspotLogout(c *fiber.Ctx) error {
	var body struct {
		Mac    string `json:"mac"`
		ZoneID string `json:"zone_id"`
	}
	if err := c.BodyParser(&body); err != nil || body.Mac == "" {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"success": false, "error": "mac is required"})
	}

	zone, err := resolveHotspotZone(c, body.ZoneID)
	if err != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{"success": false, "error": "No zones configured"})
	}

	if err := mikrotikSvc.DisconnectClient(zone, body.Mac); err != nil {
		log.Printf("[Hotspot] Failed to disconnect client %s: %v", body.Mac, err)
		if config.Config.AppEnv == "local" {
			log.Printf("[Hotspot] Dev mode: bypassing disconnect failure.")
			return c.JSON(fiber.Map{"success": true})
		}
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{"success": false, "error": err.Error()})
	}

	return c.JSON(fiber.Map{"success": true})
}
